from base import Time
 
fla = Time("Flamengo", "fla.png", "BRA", ranking_cbf=1)
palmeiras = Time("Palmeiras", "palmeiras.png", "BRA", ranking_cbf=2)
atletico = Time("Atlético-MG", "atletico.png", "BRA", ranking_cbf=3)
atlpr = Time("Athlético", "atlpr.png", "BRA", ranking_cbf=5)
santos = Time('Santos', 'santos.png', 'BRA', ranking=8, ranking_cbf=6)
saopaulo = Time('São Paulo', 'saopaulo.png', 'BRA', ranking=13, ranking_cbf=7)
fluminense = Time("Fluminense", "fluminense.png", "BRA", ranking_cbf=9)
corinthians = Time("Corinthians", "corinthians.png", "BRA", ranking_cbf=10)
fortaleza = Time("Fortaleza", "fortaleza.png", "BRA", ranking_cbf=11)
bahia = Time("Bahia", "bahia.png", "BRA", ranking_cbf=12) # imagem
ceara = Time("Ceará", "ceara.png", "BRA", ranking_cbf=13)
cruzeiro = Time("Cruzeiro", "cruzeiro.png", "BRA", ranking_cbf=14)
ammg = Time("América Mineiro", "ammg.gif", "BRA", True, ranking_cbf=15)
atlego = Time("Atlético Goianiense", "atlego.png", "BRA", ranking_cbf=16)
botafogo = Time("Botafogo", "botafogo.gif", "BRA", ranking_cbf=18) # imagem
bragantino = Time("RB Bragantino", "bragantino.png", "BRA", ranking_cbf=20)
cuiaba_mt = Time("Cuiabá", "cuiaba_mt.png", "BRA", ranking_cbf=22)
coritiba = Time("Coritiba", "coritiba.png", "BRA", ranking_cbf=26)
csa = Time("CSA", "csa.png", "BRA", ranking_cbf=30)
vilanova = Time("Vila Nova", "vilanova.png", "BRA", ranking_cbf=31)
remo = Time("Remo", "remo.png", "BRA", ranking_cbf=42)
tombense_mg = Time("Tombense", "tombense_mg.png", "BRA", ranking_cbf=49)
juazeirense_ba = Time("Juazeirense", "juazeirense_ba.png", "BRA", ranking_cbf=59)
brasiliense = Time("Brasiliense", "brasiliense.png", "BRA", ranking_cbf=63)
altos_pi = Time("Altos", "altos_pi.png", "BRA", ranking_cbf=66)
portuguesa_rj = Time("Portuguesa-RJ", "portuguesa_rj.png", "BRA", ranking_cbf=122)
tocantinopolis = Time("Tocantinopolis", "tocantinopolis.png", "BRA", ranking_cbf=146)
ceilandia_df = Time("Ceilândia", "ceilandia_df.jpg", "BRA", ranking_cbf=169)
azuriz_pr = Time("Azuriz", "azuriz_pr.png", "BRA")
juventude = Time("Juventude", "juventude.png", "BRA", ranking_cbf=24)
goias = Time("Goiás", "goias.png", "BRA", ranking_cbf=23)
vitoria = Time("Vitória", "vitoria.png", "BRA", ranking_cbf=25)
inter = Time("Internacional", "interrs.png", "BRA", ranking_cbf=8)